FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache git

COPY package*.json ./
COPY packages/database/package.json ./packages/database/
COPY packages/events/package.json ./packages/events/

RUN npm ci

COPY . .

RUN npm install

RUN npm run build

EXPOSE 8080

CMD ["node", "services/api-gateway/dist/index.js"]