/**
 * lib/notifications/notification-types.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Enterprise Notification Type Registry — Single Source of Truth
 *
 * Every notification event in the platform MUST be registered here.
 * The registry maps each event to its visual representation, routing,
 * and default delivery preferences.
 *
 * CONVENTION:
 *   Module.ACTION  →  e.g. "CRM.LEAD_CREATED", "INBOX.MESSAGE_RECEIVED"
 */

// ─── Notification Category ──────────────────────────────────────────────────

export type NotificationCategory =
  | "CRM"
  | "INBOX"
  | "AUTOMATION"
  | "AI_ENGINE"
  | "FINANCE"
  | "MARKETING"
  | "CALENDAR"
  | "CONTENT"
  | "IAM"
  | "SYSTEM"
  | "OPERATIONS"
  | "HR"
  | "SALES"
  | "SECURITY";

// ─── Notification Priority ─────────────────────────────────────────────────

export type NotificationPriority = "LOW" | "NORMAL" | "HIGH" | "URGENT";

// ─── Delivery Channel ───────────────────────────────────────────────────────

export type DeliveryChannel = "IN_APP" | "EMAIL" | "PUSH" | "WEBHOOK";

// ─── Digest Frequency ───────────────────────────────────────────────────────

export type DigestFrequency = "IMMEDIATE" | "HOURLY" | "DAILY" | "WEEKLY";

// ─── Event Type Registry ────────────────────────────────────────────────────

export interface NotificationEventMeta {
  /** Human-readable label for the event */
  label: string;
  /** Module/category this event belongs to */
  category: NotificationCategory;
  /** Lucide icon name for visual rendering */
  icon: string;
  /** Tailwind color class for the icon badge */
  color: string;
  /** Default priority level */
  defaultPriority: NotificationPriority;
  /** Default delivery channels for new users */
  defaultChannels: readonly DeliveryChannel[];
  /** URL template — {id} placeholders resolved at emission time */
  linkTemplate?: string;
  /** Whether this event can be disabled by users */
  userConfigurable: boolean;
  /** Short description for the preferences UI */
  description: string;
}

/**
 * MASTER REGISTRY — Every notification event in the platform.
 *
 * To add a new event:
 *   1. Add the key here
 *   2. Call `notifyEvent(key, { ... })` from the relevant server action
 *   3. The engine handles DB write, preference check, and delivery
 */
export const NOTIFICATION_EVENTS = {

  // ── CRM ──────────────────────────────────────────────────────────────────
  "CRM.LEAD_CREATED": {
    label: "Nuevo Lead Creado",
    category: "CRM",
    icon: "UserPlus",
    color: "text-blue-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm/leads?id={leadId}",
    userConfigurable: true,
    description: "Cuando se crea un nuevo lead en el pipeline",
  },
  "CRM.LEAD_ASSIGNED": {
    label: "Lead Asignado",
    category: "CRM",
    icon: "UserCheck",
    color: "text-blue-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/crm/leads?id={leadId}",
    userConfigurable: true,
    description: "Cuando te asignan un lead para seguimiento",
  },
  "CRM.STAGE_CHANGED": {
    label: "Etapa del Lead Actualizada",
    category: "CRM",
    icon: "ArrowRightLeft",
    color: "text-indigo-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm/pipeline",
    userConfigurable: true,
    description: "Cuando un lead avanza o retrocede en el pipeline",
  },
  "CRM.LEAD_SCORED": {
    label: "Lead Score Actualizado",
    category: "CRM",
    icon: "TrendingUp",
    color: "text-amber-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm/scoring",
    userConfigurable: true,
    description: "Cuando el score de un lead cambia significativamente",
  },
  "CRM.LEAD_STALE": {
    label: "Lead Sin Actividad",
    category: "CRM",
    icon: "Clock",
    color: "text-orange-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm/leads",
    userConfigurable: true,
    description: "Cuando un lead lleva más de X días sin actividad",
  },
  "CRM.CONTACT_MERGED": {
    label: "Contactos Fusionados",
    category: "CRM",
    icon: "GitMerge",
    color: "text-cyan-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm",
    userConfigurable: true,
    description: "Cuando dos contactos duplicados son fusionados",
  },
  "CRM.CONTACT_BLACKLISTED": {
    label: "Contacto en Lista Negra",
    category: "CRM",
    icon: "Ban",
    color: "text-red-500",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/crm",
    userConfigurable: true,
    description: "Cuando un contacto es añadido a la lista negra",
  },

  // ── SALES ────────────────────────────────────────────────────────────────
  "SALES.DEAL_WON": {
    label: "¡Deal Cerrado! 🎉",
    category: "SALES",
    icon: "Trophy",
    color: "text-emerald-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/crm?id={dealId}",
    userConfigurable: true,
    description: "Cuando un deal se cierra como ganado",
  },
  "SALES.DEAL_LOST": {
    label: "Deal Perdido",
    category: "SALES",
    icon: "XCircle",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/crm?id={dealId}",
    userConfigurable: true,
    description: "Cuando un deal se cierra como perdido",
  },
  "SALES.DEAL_STAGNANT": {
    label: "Negocio Sin Movimiento",
    category: "SALES",
    icon: "Pause",
    color: "text-slate-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/crm/pipeline",
    userConfigurable: true,
    description: "Cuando un negocio lleva días sin avance en el pipeline",
  },
  "SALES.PROPOSAL_VIEWED": {
    label: "Cotización Vista por Cliente",
    category: "SALES",
    icon: "Eye",
    color: "text-sky-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/proposals?id={proposalId}",
    userConfigurable: true,
    description: "Cuando el cliente abre y visualiza una cotización",
  },
  "SALES.PROPOSAL_SIGNED": {
    label: "Cotización Firmada ✅",
    category: "SALES",
    icon: "PenLine",
    color: "text-emerald-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/proposals?id={proposalId}",
    userConfigurable: true,
    description: "Cuando el cliente firma una propuesta",
  },
  "SALES.PROPOSAL_REJECTED": {
    label: "Cotización Rechazada",
    category: "SALES",
    icon: "FileX",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/proposals?id={proposalId}",
    userConfigurable: true,
    description: "Cuando el cliente rechaza una propuesta",
  },
  "SALES.PROPOSAL_EXPIRING": {
    label: "Cotización por Vencer",
    category: "SALES",
    icon: "TimerOff",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/proposals?id={proposalId}",
    userConfigurable: true,
    description: "Cuando una cotización está a 48h de vencer",
  },
  "SALES.GOAL_REACHED": {
    label: "Meta de Ventas Alcanzada 🏆",
    category: "SALES",
    icon: "Award",
    color: "text-yellow-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/sales/goals",
    userConfigurable: true,
    description: "Cuando se alcanza el objetivo de ventas del período",
  },
  "SALES.GOAL_AT_RISK": {
    label: "Meta de Ventas en Riesgo",
    category: "SALES",
    icon: "TrendingDown",
    color: "text-orange-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/sales/goals",
    userConfigurable: true,
    description: "Cuando el avance de ventas está por debajo del objetivo",
  },
  "SALES.COMMISSION_APPROVED": {
    label: "Comisión Aprobada",
    category: "SALES",
    icon: "BadgeDollarSign",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/crm/commissions",
    userConfigurable: true,
    description: "Cuando se aprueba una comisión de ventas",
  },

  // ── INBOX ────────────────────────────────────────────────────────────────
  "INBOX.MESSAGE_RECEIVED": {
    label: "Nuevo Mensaje Recibido",
    category: "INBOX",
    icon: "MessageSquare",
    color: "text-sky-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "PUSH"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando un contacto envía un mensaje en cualquier canal",
  },
  "INBOX.CONVERSATION_ASSIGNED": {
    label: "Conversación Asignada",
    category: "INBOX",
    icon: "UserCheck",
    color: "text-sky-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando te asignan una conversación del inbox",
  },
  "INBOX.CONVERSATION_RESOLVED": {
    label: "Conversación Resuelta",
    category: "INBOX",
    icon: "CheckCircle2",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando una conversación es marcada como resuelta",
  },
  "INBOX.CONVERSATION_REOPENED": {
    label: "Conversación Reabierta",
    category: "INBOX",
    icon: "RefreshCw",
    color: "text-amber-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando el cliente responde una conversación resuelta",
  },
  "INBOX.MENTION": {
    label: "Mención en Comentario",
    category: "INBOX",
    icon: "AtSign",
    color: "text-violet-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "PUSH"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando alguien te menciona con @username en un comentario",
  },
  "INBOX.SLA_BREACH": {
    label: "⚠️ SLA Incumplido",
    category: "INBOX",
    icon: "AlertTriangle",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL", "PUSH"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: false,
    description: "Cuando una conversación supera el tiempo máximo de respuesta",
  },
  "INBOX.SLA_WARNING": {
    label: "SLA en Riesgo (80%)",
    category: "INBOX",
    icon: "AlertCircle",
    color: "text-orange-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "PUSH"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando una conversación está a punto de incumplir el SLA",
  },
  "INBOX.HUMAN_TRANSFER": {
    label: "Transferencia a Humano",
    category: "INBOX",
    icon: "PhoneForwarded",
    color: "text-orange-400",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL", "PUSH"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: false,
    description: "Cuando un agente AI solicita intervención humana",
  },
  "INBOX.CSAT_NEGATIVE": {
    label: "Reseña Negativa CSAT",
    category: "INBOX",
    icon: "ThumbsDown",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando un cliente da una calificación negativa de satisfacción",
  },
  "INBOX.TICKET_ESCALATED": {
    label: "Ticket Escalado",
    category: "INBOX",
    icon: "TrendingUp",
    color: "text-red-400",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: false,
    description: "Cuando un ticket es escalado al siguiente nivel de soporte",
  },
  "INBOX.TICKET_OVERDUE": {
    label: "Ticket Sin Respuesta",
    category: "INBOX",
    icon: "TimerOff",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/inbox?conversation={conversationId}",
    userConfigurable: true,
    description: "Cuando un ticket no ha recibido respuesta en el tiempo esperado",
  },

  // ── OPERATIONS ───────────────────────────────────────────────────────────
  "OPERATIONS.TASK_ASSIGNED": {
    label: "Tarea Asignada",
    category: "OPERATIONS",
    icon: "ClipboardList",
    color: "text-violet-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Cuando te asignan una tarea en el sistema",
  },
  "OPERATIONS.TASK_COMPLETED": {
    label: "Tarea Completada",
    category: "OPERATIONS",
    icon: "CheckSquare",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Cuando una tarea de tu equipo es marcada como completada",
  },
  "OPERATIONS.TASK_OVERDUE": {
    label: "Tarea Vencida",
    category: "OPERATIONS",
    icon: "AlertTriangle",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Cuando una tarea supera su fecha límite sin completarse",
  },
  "OPERATIONS.TASK_DUE_SOON": {
    label: "Tarea por Vencer Hoy",
    category: "OPERATIONS",
    icon: "Timer",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Recordatorio para tareas con vencimiento en las próximas horas",
  },
  "OPERATIONS.PROJECT_MILESTONE": {
    label: "Milestone de Proyecto Alcanzado",
    category: "OPERATIONS",
    icon: "Flag",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/projects",
    userConfigurable: true,
    description: "Cuando se alcanza un hito importante en un proyecto",
  },
  "OPERATIONS.PROJECT_DELAYED": {
    label: "Proyecto Retrasado",
    category: "OPERATIONS",
    icon: "CalendarOff",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/projects",
    userConfigurable: true,
    description: "Cuando un proyecto supera su fecha estimada de entrega",
  },
  "OPERATIONS.KANBAN_BLOCKED": {
    label: "Tarjeta Bloqueada en Kanban",
    category: "OPERATIONS",
    icon: "Lock",
    color: "text-orange-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Cuando una tarjeta del tablero es marcada como bloqueada",
  },
  "OPERATIONS.TIMER_LIMIT_REACHED": {
    label: "Límite de Tiempo Alcanzado",
    category: "OPERATIONS",
    icon: "AlarmClock",
    color: "text-amber-500",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "PUSH"],
    linkTemplate: "/dashboard/kanban",
    userConfigurable: true,
    description: "Cuando se alcanza el límite de tiempo en una operación",
  },

  // ── AUTOMATION ───────────────────────────────────────────────────────────
  "AUTOMATION.WORKFLOW_COMPLETED": {
    label: "Workflow Completado",
    category: "AUTOMATION",
    icon: "CheckCircle2",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/automation",
    userConfigurable: true,
    description: "Cuando un workflow se ejecuta exitosamente",
  },
  "AUTOMATION.WORKFLOW_FAILED": {
    label: "Workflow Fallido",
    category: "AUTOMATION",
    icon: "XOctagon",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/automation",
    userConfigurable: true,
    description: "Cuando un workflow falla durante la ejecución",
  },
  "AUTOMATION.CAMPAIGN_LAUNCHED": {
    label: "Campaña Lanzada",
    category: "AUTOMATION",
    icon: "Rocket",
    color: "text-violet-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/marketing/campaigns",
    userConfigurable: true,
    description: "Cuando una campaña programada se ejecuta",
  },

  // ── AI ENGINE ────────────────────────────────────────────────────────────
  "AI.AGENT_SUSPENDED": {
    label: "Agente AI Suspendido",
    category: "AI_ENGINE",
    icon: "BotOff",
    color: "text-amber-500",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: true,
    description: "Cuando un agente se suspende por frustración o circuit breaker",
  },
  "AI.CIRCUIT_BREAKER_OPEN": {
    label: "Circuit Breaker Activado",
    category: "AI_ENGINE",
    icon: "ShieldAlert",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: false,
    description: "Cuando el circuit breaker se abre por fallos repetidos del proveedor AI",
  },
  "AI.QUOTA_EXCEEDED": {
    label: "Cuota de Tokens IA Excedida",
    category: "AI_ENGINE",
    icon: "Gauge",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: false,
    description: "Cuando se supera el límite de tokens o peticiones de la API AI",
  },
  "AI.HALLUCINATION_FLAG": {
    label: "Respuesta IA Marcada (Flag)",
    category: "AI_ENGINE",
    icon: "Flag",
    color: "text-orange-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: true,
    description: "Cuando una respuesta del agente AI es marcada por revisión humana",
  },
  "AI.AGENT_TRAINED": {
    label: "Agente IA Entrenado / Listo",
    category: "AI_ENGINE",
    icon: "GraduationCap",
    color: "text-teal-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: true,
    description: "Cuando un agente IA completa su ciclo de entrenamiento",
  },
  "AI.KB_UPDATED": {
    label: "Base de Conocimiento Actualizada",
    category: "AI_ENGINE",
    icon: "BookOpen",
    color: "text-cyan-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/settings/agents",
    userConfigurable: true,
    description: "Cuando la base de conocimiento de un agente es actualizada",
  },

  // ── FINANCE ──────────────────────────────────────────────────────────────
  "FINANCE.INVOICE_CREATED": {
    label: "Nueva Factura Creada",
    category: "FINANCE",
    icon: "FileText",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/invoices?id={invoiceId}",
    userConfigurable: true,
    description: "Cuando se genera una nueva factura",
  },
  "FINANCE.INVOICE_PAID": {
    label: "Factura Pagada ✅",
    category: "FINANCE",
    icon: "CircleDollarSign",
    color: "text-emerald-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/invoices?id={invoiceId}",
    userConfigurable: true,
    description: "Cuando un cliente paga una factura",
  },
  "FINANCE.INVOICE_OVERDUE": {
    label: "Factura Vencida",
    category: "FINANCE",
    icon: "AlertCircle",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/invoices?id={invoiceId}",
    userConfigurable: true,
    description: "Cuando una factura supera la fecha de vencimiento",
  },
  "FINANCE.INVOICE_DUE_SOON": {
    label: "Factura por Vencer (48h)",
    category: "FINANCE",
    icon: "CalendarClock",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/invoices?id={invoiceId}",
    userConfigurable: true,
    description: "Recordatorio de factura que vence en las próximas 48 horas",
  },
  "FINANCE.PAYMENT_RECEIVED": {
    label: "Pago Recibido 💰",
    category: "FINANCE",
    icon: "BadgeDollarSign",
    color: "text-emerald-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/treasury",
    userConfigurable: true,
    description: "Cuando se registra un pago de cliente",
  },
  "FINANCE.PAYMENT_FAILED": {
    label: "Pago Rechazado / Fallido",
    category: "FINANCE",
    icon: "CreditCard",
    color: "text-red-400",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/invoices",
    userConfigurable: false,
    description: "Cuando un pago es rechazado por el procesador",
  },
  "FINANCE.PAYROLL_PROCESSED": {
    label: "Nómina Procesada",
    category: "FINANCE",
    icon: "Wallet",
    color: "text-purple-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/payroll",
    userConfigurable: true,
    description: "Cuando se procesa el ciclo de nómina",
  },
  "FINANCE.PAYROLL_DUE": {
    label: "Nómina por Procesar",
    category: "FINANCE",
    icon: "CalendarClock",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/payroll",
    userConfigurable: true,
    description: "Recordatorio de procesamiento de nómina próximo",
  },
  "FINANCE.EXPENSE_APPROVED": {
    label: "Gasto Aprobado",
    category: "FINANCE",
    icon: "BadgeCheck",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/treasury",
    userConfigurable: true,
    description: "Cuando un gasto pendiente es aprobado",
  },
  "FINANCE.EXPENSE_REJECTED": {
    label: "Gasto Rechazado",
    category: "FINANCE",
    icon: "Ban",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/treasury",
    userConfigurable: true,
    description: "Cuando un gasto es rechazado",
  },
  "FINANCE.BUDGET_EXCEEDED": {
    label: "Presupuesto Excedido",
    category: "FINANCE",
    icon: "TrendingUp",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/treasury",
    userConfigurable: false,
    description: "Cuando se supera el presupuesto asignado a un área",
  },
  "FINANCE.TREASURY_LOW_BALANCE": {
    label: "Saldo Bajo en Tesorería",
    category: "FINANCE",
    icon: "AlertTriangle",
    color: "text-orange-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/treasury",
    userConfigurable: false,
    description: "Cuando el saldo de tesorería cae por debajo del mínimo configurado",
  },

  // ── MARKETING ────────────────────────────────────────────────────────────
  "MARKETING.SOCIAL_PUBLISHED": {
    label: "Post Social Publicado",
    category: "MARKETING",
    icon: "Share2",
    color: "text-pink-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/marketing",
    userConfigurable: true,
    description: "Cuando un post programado se publica en redes sociales",
  },
  "MARKETING.SOCIAL_FAILED": {
    label: "Error al Publicar en Redes",
    category: "MARKETING",
    icon: "AlertCircle",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/marketing",
    userConfigurable: true,
    description: "Cuando falla la publicación de un post programado",
  },
  "MARKETING.EMAIL_BLAST_SENT": {
    label: "Email Blast Enviado",
    category: "MARKETING",
    icon: "Send",
    color: "text-violet-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/marketing/campaigns",
    userConfigurable: true,
    description: "Cuando un email masivo se envía exitosamente",
  },
  "MARKETING.EMAIL_BOUNCE_HIGH": {
    label: "Alta Tasa de Rebote en Email",
    category: "MARKETING",
    icon: "MailX",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/marketing/campaigns",
    userConfigurable: true,
    description: "Cuando el porcentaje de rebote supera el umbral configurado",
  },
  "MARKETING.AD_BUDGET_DEPLETED": {
    label: "Presupuesto Publicitario Agotado",
    category: "MARKETING",
    icon: "Wallet",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/marketing/spend",
    userConfigurable: false,
    description: "Cuando el presupuesto de anuncios es consumido en su totalidad",
  },
  "MARKETING.CAMPAIGN_COMPLETED": {
    label: "Campaña Completada",
    category: "MARKETING",
    icon: "CheckCircle2",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/marketing/campaigns",
    userConfigurable: true,
    description: "Cuando una campaña finaliza su período de ejecución",
  },
  "MARKETING.CAMPAIGN_PAUSED": {
    label: "Campaña Pausada",
    category: "MARKETING",
    icon: "PauseCircle",
    color: "text-amber-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/marketing/campaigns",
    userConfigurable: true,
    description: "Cuando una campaña activa es pausada",
  },

  // ── CALENDAR ─────────────────────────────────────────────────────────────
  "CALENDAR.EVENT_CREATED": {
    label: "Nuevo Evento",
    category: "CALENDAR",
    icon: "CalendarPlus",
    color: "text-teal-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/events?date={date}",
    userConfigurable: true,
    description: "Cuando se crea un evento en el calendario",
  },
  "CALENDAR.REMINDER": {
    label: "Recordatorio de Evento",
    category: "CALENDAR",
    icon: "AlarmClock",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL", "PUSH"],
    linkTemplate: "/dashboard/events?date={date}",
    userConfigurable: true,
    description: "Recordatorio antes de un evento programado",
  },
  "CALENDAR.EVENT_CANCELLED": {
    label: "Evento Cancelado",
    category: "CALENDAR",
    icon: "CalendarOff",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/events",
    userConfigurable: true,
    description: "Cuando un evento del calendario es cancelado",
  },

  // ── CONTENT ──────────────────────────────────────────────────────────────
  "CONTENT.POST_PUBLISHED": {
    label: "Post Publicado",
    category: "CONTENT",
    icon: "BookOpen",
    color: "text-teal-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/posts?id={postId}",
    userConfigurable: true,
    description: "Cuando un artículo del blog se publica",
  },
  "CONTENT.COMMENT_NEW": {
    label: "Nuevo Comentario",
    category: "CONTENT",
    icon: "MessageCircle",
    color: "text-sky-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/posts?id={postId}",
    userConfigurable: true,
    description: "Cuando alguien comenta en un post",
  },
  "CONTENT.VIDEO_RENDER_COMPLETE": {
    label: "Video Renderizado Listo",
    category: "CONTENT",
    icon: "Video",
    color: "text-violet-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/tools/video-editor",
    userConfigurable: true,
    description: "Cuando un video termina de renderizarse",
  },
  "CONTENT.VIDEO_RENDER_FAILED": {
    label: "Error al Renderizar Video",
    category: "CONTENT",
    icon: "VideoOff",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/tools/video-editor",
    userConfigurable: true,
    description: "Cuando falla el proceso de renderizado de un video",
  },
  "CONTENT.MEDIA_STORAGE_WARN": {
    label: "Almacenamiento al 80%",
    category: "CONTENT",
    icon: "HardDrive",
    color: "text-orange-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/media",
    userConfigurable: true,
    description: "Cuando el almacenamiento de medios supera el 80% de capacidad",
  },

  // ── HR ───────────────────────────────────────────────────────────────────
  "HR.TIME_OFF_REQUESTED": {
    label: "Permiso de Ausencia Solicitado",
    category: "HR",
    icon: "CalendarX",
    color: "text-amber-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/payroll",
    userConfigurable: true,
    description: "Cuando un empleado solicita días de ausencia",
  },
  "HR.TIME_OFF_APPROVED": {
    label: "Permiso de Ausencia Aprobado",
    category: "HR",
    icon: "CalendarCheck",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/payroll",
    userConfigurable: true,
    description: "Cuando un permiso de ausencia es aprobado",
  },
  "HR.TIME_OFF_REJECTED": {
    label: "Permiso de Ausencia Rechazado",
    category: "HR",
    icon: "CalendarX",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/payroll",
    userConfigurable: true,
    description: "Cuando un permiso de ausencia es rechazado",
  },
  "HR.EMPLOYEE_ONBOARDED": {
    label: "Nuevo Empleado Incorporado",
    category: "HR",
    icon: "UserPlus",
    color: "text-teal-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/admin/team",
    userConfigurable: true,
    description: "Cuando un nuevo empleado completa el proceso de incorporación",
  },
  "HR.EMPLOYEE_OFFBOARDED": {
    label: "Empleado Dado de Baja",
    category: "HR",
    icon: "UserMinus",
    color: "text-slate-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/team",
    userConfigurable: true,
    description: "Cuando se registra la baja de un empleado",
  },
  "HR.CONTRACT_EXPIRING": {
    label: "Contrato por Expirar",
    category: "HR",
    icon: "FileWarning",
    color: "text-amber-500",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/team",
    userConfigurable: true,
    description: "Cuando un contrato de empleado está próximo a vencer",
  },
  "HR.PERFORMANCE_REVIEW_DUE": {
    label: "Evaluación de Desempeño Pendiente",
    category: "HR",
    icon: "ClipboardCheck",
    color: "text-violet-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/admin/team",
    userConfigurable: true,
    description: "Cuando vence el período para completar una evaluación de desempeño",
  },

  // ── IAM / TEAM ───────────────────────────────────────────────────────────
  "IAM.USER_INVITED": {
    label: "Nuevo Miembro Invitado",
    category: "IAM",
    icon: "UserPlus",
    color: "text-cyan-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/users",
    userConfigurable: true,
    description: "Cuando se invita a un nuevo miembro al equipo",
  },
  "IAM.MEMBER_JOINED": {
    label: "Nuevo Miembro Unido al Equipo",
    category: "IAM",
    icon: "Users",
    color: "text-teal-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/users",
    userConfigurable: true,
    description: "Cuando un miembro invitado acepta y se une al equipo",
  },
  "IAM.MEMBER_REMOVED": {
    label: "Miembro Eliminado del Equipo",
    category: "IAM",
    icon: "UserMinus",
    color: "text-red-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/users",
    userConfigurable: true,
    description: "Cuando un miembro del equipo es eliminado de la organización",
  },
  "IAM.ROLE_CHANGED": {
    label: "Rol / Permisos Actualizado",
    category: "IAM",
    icon: "Shield",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/users",
    userConfigurable: false,
    description: "Cuando tu rol o permisos son modificados",
  },

  // ── SECURITY ─────────────────────────────────────────────────────────────
  "SECURITY.LOGIN_UNUSUAL": {
    label: "Inicio de Sesión Inusual",
    category: "SECURITY",
    icon: "AlertTriangle",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL", "PUSH"],
    linkTemplate: "/dashboard/security",
    userConfigurable: false,
    description: "Inicio de sesión desde dispositivo o ubicación desconocida",
  },
  "SECURITY.MFA_DISABLED": {
    label: "MFA Desactivado",
    category: "SECURITY",
    icon: "ShieldOff",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/security",
    userConfigurable: false,
    description: "Cuando la autenticación de dos factores es desactivada en una cuenta",
  },
  "SECURITY.API_KEY_USED": {
    label: "Clave API Utilizada",
    category: "SECURITY",
    icon: "Key",
    color: "text-amber-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    linkTemplate: "/dashboard/security",
    userConfigurable: true,
    description: "Cuando una clave API es utilizada para autenticar una petición",
  },
  "SECURITY.PASSWORD_CHANGED": {
    label: "Contraseña Cambiada",
    category: "SECURITY",
    icon: "Lock",
    color: "text-amber-400",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/security",
    userConfigurable: false,
    description: "Cuando la contraseña de una cuenta es modificada",
  },
  "SECURITY.DATA_EXPORTED": {
    label: "Exportación de Datos Realizada",
    category: "SECURITY",
    icon: "Download",
    color: "text-amber-500",
    defaultPriority: "HIGH",
    defaultChannels: ["IN_APP", "EMAIL"],
    linkTemplate: "/dashboard/security",
    userConfigurable: true,
    description: "Cuando se realiza una exportación masiva de datos",
  },
  "SECURITY.SUSPICIOUS_ACTIVITY": {
    label: "Actividad Sospechosa Detectada",
    category: "SECURITY",
    icon: "ShieldAlert",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL", "PUSH"],
    linkTemplate: "/dashboard/security",
    userConfigurable: false,
    description: "Detección de actividad anómala o sospechosa en la cuenta",
  },

  // ── SYSTEM ───────────────────────────────────────────────────────────────
  "SYSTEM.MAINTENANCE": {
    label: "Mantenimiento Programado",
    category: "SYSTEM",
    icon: "Wrench",
    color: "text-slate-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    userConfigurable: false,
    description: "Avisos de mantenimiento y actualizaciones del sistema",
  },
  "SYSTEM.UPDATE": {
    label: "Actualización de Plataforma",
    category: "SYSTEM",
    icon: "RefreshCw",
    color: "text-teal-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    userConfigurable: false,
    description: "Nuevas funcionalidades y mejoras disponibles en la plataforma",
  },
  "SYSTEM.BACKUP_DONE": {
    label: "Respaldo Automático Completado",
    category: "SYSTEM",
    icon: "HardDrive",
    color: "text-emerald-400",
    defaultPriority: "LOW",
    defaultChannels: ["IN_APP"],
    userConfigurable: true,
    description: "Cuando se completa el respaldo programado de datos",
  },
  "SYSTEM.BACKUP_FAILED": {
    label: "Error en Respaldo del Sistema",
    category: "SYSTEM",
    icon: "ServerCrash",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    userConfigurable: false,
    description: "Cuando falla el proceso de respaldo de datos",
  },
  "SYSTEM.INTEGRATION_DOWN": {
    label: "Integración Externa Caída",
    category: "SYSTEM",
    icon: "Unplug",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    userConfigurable: false,
    description: "Cuando una integración de terceros deja de responder",
  },
  "SYSTEM.INTEGRATION_RECOVERED": {
    label: "Integración Externa Recuperada",
    category: "SYSTEM",
    icon: "PlugZap",
    color: "text-emerald-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    userConfigurable: true,
    description: "Cuando una integración previamente caída se recupera",
  },
  "SYSTEM.ALERT": {
    label: "Alerta Crítica del Sistema",
    category: "SYSTEM",
    icon: "ServerCrash",
    color: "text-red-500",
    defaultPriority: "URGENT",
    defaultChannels: ["IN_APP", "EMAIL"],
    userConfigurable: false,
    description: "Alertas críticas de infraestructura y sistema",
  },
  "SYSTEM.WELCOME": {
    label: "Bienvenida",
    category: "SYSTEM",
    icon: "Sparkles",
    color: "text-teal-400",
    defaultPriority: "NORMAL",
    defaultChannels: ["IN_APP"],
    userConfigurable: false,
    description: "Mensaje de bienvenida para nuevos usuarios",
  },
} as const;

export type NotificationEventType = keyof typeof NOTIFICATION_EVENTS;

// ─── Helper: Get category icon and color ─────────────────────────────────────

export const CATEGORY_META: Record<NotificationCategory, { label: string; icon: string; color: string }> = {
  CRM:        { label: "CRM",                icon: "Users",          color: "text-blue-400" },
  INBOX:      { label: "Inbox & Soporte",    icon: "MessageSquare",  color: "text-sky-400" },
  AUTOMATION: { label: "Automatización",     icon: "Workflow",       color: "text-violet-400" },
  AI_ENGINE:  { label: "Agentes IA",         icon: "Bot",            color: "text-amber-400" },
  FINANCE:    { label: "Finanzas",           icon: "DollarSign",     color: "text-emerald-400" },
  MARKETING:  { label: "Marketing",          icon: "Megaphone",      color: "text-pink-400" },
  CALENDAR:   { label: "Calendario",         icon: "Calendar",       color: "text-teal-400" },
  CONTENT:    { label: "Contenido & Media",  icon: "FileText",       color: "text-cyan-400" },
  IAM:        { label: "Equipo & Accesos",   icon: "Shield",         color: "text-indigo-400" },
  SYSTEM:     { label: "Sistema",            icon: "Settings",       color: "text-slate-400" },
  OPERATIONS: { label: "Operaciones",        icon: "Briefcase",      color: "text-violet-400" },
  HR:         { label: "RRHH",               icon: "Users",          color: "text-rose-400" },
  SALES:      { label: "Ventas",             icon: "TrendingUp",     color: "text-amber-400" },
  SECURITY:   { label: "Seguridad",          icon: "ShieldAlert",    color: "text-red-400" },
};
