#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# LegacyMark — Production Secrets Generator
# ══════════════════════════════════════════════════════════════════════════════
# Usage: bash scripts/generate-production-secrets.sh >> .env
# WARNING: Run ONCE. Do NOT commit the output to git.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

echo ""
echo "# ═══════════════════════════════════════════════════"
echo "# LegacyMark Production Secrets — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Generated by scripts/generate-production-secrets.sh"
echo "# ═══════════════════════════════════════════════════"
echo ""
echo "# ── Database ─────────────────────────────────────"
echo "POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/' | cut -c1-32)"
echo ""
echo "# ── Authentication ───────────────────────────────"
echo "JWT_SECRET=$(openssl rand -hex 64)"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "AUTH_SECRET=$(openssl rand -base64 32)"
echo "INTERNAL_SECRET=$(openssl rand -hex 32)"
echo ""
echo "# ── Payments (Bold Colombia) ─────────────────────"
echo "# IMPORTANT: Replace with the real HMAC key from your Bold dashboard."
echo "# Bold Dashboard: https://dashboard.bold.co → Integraciones → Webhook → Clave HMAC"
echo "PAYMENT_HMAC_SECRET=REPLACE_WITH_REAL_BOLD_HMAC_KEY"
echo ""
echo "# ── Application ──────────────────────────────────"
echo "NEXTAUTH_URL=https://legacymarksas.com"
echo "NODE_ENV=production"
echo ""
echo "# ── Monitoring (Change these!) ────────────────────"
echo "GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d '=+/' )"
