services:
  vault:
    image: hashicorp/vault:1.16
    container_name: legacymark-vault
    restart: always
    user: "0:0"
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_API_ADDR: 'http://127.0.0.1:8200'
    volumes:
      - ./config:/vault/config:ro
      - ./data:/vault/data:rw
      - ./policies:/vault/policies:ro
      - ./scripts:/vault/scripts:ro
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK
    command: server
    networks:
      - legacymark_vault_net

networks:
  legacymark_vault_net:
    name: legacymark_vault_net
    driver: bridge
