apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: agency-v1
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-internal-mesh
  namespace: agency-v1
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/agency-v1/sa/*"]
